module Api.Data exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: apidata.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias CurrentUser =
    { username : String -- 1
    }


currentUserDecoder : JD.Decoder CurrentUser
currentUserDecoder =
    JD.lazy <| \_ -> decode CurrentUser
        |> required "username" JD.string ""


currentUserEncoder : CurrentUser -> JE.Value
currentUserEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "username" JE.string "" v.username)
        ]


type alias UserProfile =
    { about : String -- 1
    , avatar : String -- 2
    , language : String -- 3
    , location : String -- 4
    , organization : String -- 5
    , phoneNumber : String -- 6
    , realName : String -- 7
    , twitterUrl : String -- 8
    , facebookUrl : String -- 9
    }


userProfileDecoder : JD.Decoder UserProfile
userProfileDecoder =
    JD.lazy <| \_ -> decode UserProfile
        |> required "about" JD.string ""
        |> required "avatar" JD.string ""
        |> required "language" JD.string ""
        |> required "location" JD.string ""
        |> required "organization" JD.string ""
        |> required "phoneNumber" JD.string ""
        |> required "realName" JD.string ""
        |> required "twitterUrl" JD.string ""
        |> required "facebookUrl" JD.string ""


userProfileEncoder : UserProfile -> JE.Value
userProfileEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "about" JE.string "" v.about)
        , (requiredFieldEncoder "avatar" JE.string "" v.avatar)
        , (requiredFieldEncoder "language" JE.string "" v.language)
        , (requiredFieldEncoder "location" JE.string "" v.location)
        , (requiredFieldEncoder "organization" JE.string "" v.organization)
        , (requiredFieldEncoder "phoneNumber" JE.string "" v.phoneNumber)
        , (requiredFieldEncoder "realName" JE.string "" v.realName)
        , (requiredFieldEncoder "twitterUrl" JE.string "" v.twitterUrl)
        , (requiredFieldEncoder "facebookUrl" JE.string "" v.facebookUrl)
        ]
